project:
  type: website

website:
  title: "马南冲"
  site-url: https://manjis.netlify.app/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mananchong/quarto_blog
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: ember.scss
    css: styles.css

editor: visual

execute:
  freeze: auto
