---
title: Rdatatable中按行求和
date: "2017-08-26"
categories:
  - rstats
  - rdatatable
  - code
---

在实际工作中会遇到按行求和的情况，如下表所示，知道了门诊人次，急诊人次，想在最右边加一列门急诊合计人次。

```{r}
library(data.table)
menJiZhen <- data.table(
    keShi = c("内科", "外科", "骨科", "妇产科", "儿科", "皮肤科"),
    menZhenRenCi = c(555, 666, 777, 888, 999, 111),
    jiZhenRenCi = c(55, 66, 77, 88, 99, NA)
)
knitr::kable(menJiZhen)
```

## 采用`rowSums`函数

```{r}
methods01 <- copy(menJiZhen)
methods01[
    ,
    heJi := rowSums(.SD, na.rm = TRUE),
    .SDcols = c("menZhenRenCi", "jiZhenRenCi")
]
knitr::kable(methods01)
```

如果要计算的列中包含空值，可以通过设置 `rowSums` 函数的 `na.rm = TRUE` 参数来排除空值。示例中，皮肤科没有急诊，默认情况下（ `na.rm = FALSE` ），计算结果是 `NA`，不是希望的结果。

## 采用 `Reduce` 和 `+` 函数

```{r}
methods02 <- copy(menJiZhen)
sumCols <- c("menZhenRenCi", "jiZhenRenCi")
for (col in sumCols) {
    set(
        methods02,
        i = which(is.na(methods02[[col]])),
        j = col,
        0L
    )
}
methods02[
    ,
    heJi := Reduce(`+`, .SD),
    .SDcols = sumCols
]
knitr::kable(methods02)
```

这种方法里，也是首先把空值替换成 0 ， 再用 `Reduce` 和 `+` 函数来求和。

两种方法里，第一种得到的合计列，是 `double` 类型的，而第二种方法里是 `integer` 类型的。

参考：[Sum of integer columns is double](https://stackoverflow.com/questions/45960913/sum-of-integer-columns-is-double/45961107#45961107)
